on:
  push:
  workflow_dispatch:
    inputs:
      skip:
        required: true
        default: true

jobs:
  build-wheels:
    name: "${{ matrix.os }} :: ${{ matrix.platform }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # emulated linux: generate 6 matrix combinations with qemu on ubuntu:
        arch: ["aarch64", "ppc64le", "s390x"]
        platform: ["manylinux", "musllinux"]
        os: [ubuntu-latest]
        use_qemu: [true]
        exclude:
          - os: ubuntu-latest
            use_qemu: true #fromJSON(${{ github.event.inputs.skip }})
    steps:
      - run: echo ${{ github.event.inputs.skip }}